/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_content_delivery_bucket: 'caseexplorer-hosting-nocf-prod',
  aws_content_delivery_bucket_region: 'us-east-1',
  aws_content_delivery_url:
    'http://caseexplorer-hosting-nocf-prod.s3-website-us-east-1.amazonaws.com',
  aws_cloud_logic_custom: [
    {
      name: 'caseexplorerapi',
      endpoint: 'https://u58tbar758.execute-api.us-east-1.amazonaws.com/prod',
      region: 'us-east-1'
    }
  ],
  aws_appsync_graphqlEndpoint:
    'https://lv7xshcs4jgppl6wrqj7w6lxnq.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-lgd6oddwivea3lw4pdon2tncuy'
};

export default awsmobile;
